FROM tomcat:8.5

RUN ["rm", "-fr", "/usr/local/tomcat/webapps/ROOT"]

COPY init.sh /tmp/init.sh
COPY server.xml conf/
COPY target/aggregate-mysql-1.0.1 webapps/ROOT/

EXPOSE 8443
ENTRYPOINT ["/tmp/init.sh"]
CMD ["/usr/local/tomcat/bin/catalina.sh", "run"]
